perk_list = {
    0: "Devoted",
    1: "Rapid",
    2: "Efficient",
    3: "Hoarding",
    4: "Relentless",
    5: "Reflexes",
    6: "Genocidal",
    7: "Tinker",
    8: "Taunting",
    9: "Fatiguing",
    10: "Mysterious",
    11: "Wise",
    12: "Junk Food",
    13: "Equilibrium",
    14: "Breakdown",
    15: "Flanking",
    16: "Furnace",
    17: "Inaccurate",
    18: "Brief Respite",
    19: "Blunted",
    20: "Caroming",
    21: "Lucky",
    22: "Lunging",
    23: "Ruthless",
    24: "Confused",
    25: "Trophy-taker's",
    26: "Imp Souled",
    27: "Enlightened",
    28: "Turtling",
    29: "Undead Bait",
    30: "Enhanced Efficient",
    31: "Ultimatums",
    32: "Fortune",
    33: "Cautious",
    34: "Dragon Slayer",
    35: "Looting",
    36: "Profane",
    37: "Bulwark",
    38: "Mobile",
    39: "No effect",
    40: "Scavenging",
    41: "Impatient",
    42: "Charitable",
    43: "Aftershock",
    44: "Brassican",
    45: "Glow Worm",
    46: "Absorbative",
    47: "Polishing",
    48: "Biting",
    49: "Spendthrift",
    50: "Shield Bashing",
    51: "Demon Bait",
    52: "Demon Slayer",
    53: "Precise",
    54: "Clear Headed",
    55: "Energising",
    56: "Cheapskate",
    57: "Undead Slayer",
    58: "Invigorating",
    59: "Antitheism",
    60: "Preparation",
    61: "Venomblood",
    62: "Planted Feet",
    63: "Honed",
    64: "Pyromaniac",
    65: "Talking",
    66: "Mediocrity",
    67: "Prosper",
    68: "Butterfingers",
    69: "Committed",
    70: "Crystal Shield",
    71: "Hallucinogenic",
    72: "Refined",
    73: "Dragon Bait",
    74: "Enhanced Devoted",
    75: "Crackling",
}
